# Generated by Django 4.2.4 on 2023-08-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_client_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='company_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
